# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "ocm-helm-toolbox"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/ocm-helm-toolbox"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/containers/image/v5/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/majewsky/gg/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-api-declarations/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-bits/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/spf13/cobra/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/containers/storage/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/inconshreveable/mousetrap/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/opencontainers/go-digest/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sergi/go-diff/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/spf13/pflag/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/check.v1/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"
